create table if not exists public.mocks (
  id bigint generated by default as identity primary key,
  path text not null,
  method text not null,
  user_id text not null default 'user-1',
  status integer not null default 200,
  headers text not null default 'Content-Type: application/json',
  body jsonb not null default '{}'::jsonb,
  rules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique(path, method, user_id)
);

alter table public.mocks enable row level security;
