create table if not exists public.mocks (
  id bigint generated by default as identity primary key,
  path text not null,
  method text not null,
  status integer not null default 200,
  headers text not null default 'Content-Type: application/json',
  body jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(path, method)
);

alter table public.mocks enable row level security;
